HelloRestApi/ViewModels/ChatViewModel.cs
using HelloRestApi.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloRestApi.ViewModels
{
    public class ChatViewModel
    {
        public IEnumerable<Hello> Helloes { get; set; }
        public string Message { get; set; }
        public string Author { get; set; }
    }
}

HelloRestApi/Controllers/HelloController.cs
using HelloRestApi.Hubs;
using HelloRestApi.Model;
using HelloRestApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloRestApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class HelloController : ControllerBase
    {
        private readonly HelloRestApiContext _context;

        public HelloController (HelloRestApiContext context)
        {
            _context = context;
        }

        // GET api/hello
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Hello>>> GetHello()
        {
            var messeges = await _context.Hello.ToListAsync();
            return Ok(messeges);
        }

        // GET api/hello/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Hello>> Get(int id)
        {
            var message = await _context.Hello.FirstOrDefaultAsync(m => m.ID == id);

            if (message == null)
            {
                return StatusCode(400, "Bad request");
            }

            return Ok(message);
        }

        // POST api/hello
        [HttpPost]
        public async Task<ActionResult> Post([FromBody] Hello value)
        {
            if (ModelState.IsValid)
            {
                _context.Hello.Add(value);
                await _context.SaveChangesAsync();
            }
            return Created(new Uri(Request.Path + "/" + (_context.Hello.Last().ID).ToString(),UriKind.Relative),value);
        }

        // PUT api/hello/5
        [HttpPut("{id}")]
        public ActionResult Put(int id, [FromBody] string value)
        {
            return StatusCode(400, "Bad request");
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public ActionResult Delete(int id)
        {
            return StatusCode(400, "Bad request");
        }
    }
}

HelloRestApi/Controllers/HelloesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelloRestApi.Model;
using HelloRestApi.Models;
using HelloRestApi.ViewModels;

namespace HelloRestApi.Controllers
{
    public class HelloesController : Controller
    {
        private readonly HelloRestApiContext _context;

        public HelloesController(HelloRestApiContext context)
        {
            _context = context;
        }

        // GET: Helloes
        public async Task<IActionResult> Index()
        {
            var myViewModel = new ChatViewModel { Helloes = await _context.Hello.ToListAsync() };

            return View(myViewModel);
        }

        // GET: Helloes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hello = await _context.Hello
                .FirstOrDefaultAsync(m => m.ID == id);
            if (hello == null)
            {
                return NotFound();
            }

            return View(hello);
        }

        // GET: Helloes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Helloes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Message,Author,TimeStamp")] Hello hello)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hello);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hello);
        }

        // GET: Helloes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hello = await _context.Hello.FindAsync(id);
            if (hello == null)
            {
                return NotFound();
            }
            return View(hello);
        }

        // POST: Helloes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Message,Author,TimeStamp")] Hello hello)
        {
            if (id != hello.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hello);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HelloExists(hello.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hello);
        }

        // GET: Helloes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hello = await _context.Hello
                .FirstOrDefaultAsync(m => m.ID == id);
            if (hello == null)
            {
                return NotFound();
            }

            return View(hello);
        }

        // POST: Helloes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hello = await _context.Hello.FindAsync(id);
            _context.Hello.Remove(hello);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HelloExists(int id)
        {
            return _context.Hello.Any(e => e.ID == id);
        }
    }
}

HelloRestApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HelloWebPage.Models;
using HelloRestApi.Model;

namespace HelloWebPage.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HelloRestApi/Views/Helloes/Create.cshtml
@model HelloRestApi.Model.Hello

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hello</h4>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col">
                <label asp-for="Message" class="control-label"></label>
                <textarea asp-for="Message" class="form-control" ></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelloRestApi/Views/Helloes/Delete.cshtml
@model HelloRestApi.Model.Hello

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hello</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HelloRestApi/Views/Helloes/Details.cshtml
@model HelloRestApi.Model.Hello

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hello</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HelloRestApi/Views/Helloes/Edit.cshtml
@model HelloRestApi.Model.Hello

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Hello</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeStamp" class="control-label"></label>
                <input asp-for="TimeStamp" class="form-control" />
                <span asp-validation-for="TimeStamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HelloRestApi/Views/Helloes/Index.cshtml
@model HelloRestApi.ViewModels.ChatViewModel


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="inbox_chat">
    <div class="chat_list active_chat">
        <div class="chat_people">
            @foreach (var item in Model.Helloes)
            {
                <div class="chat_ib mb-3">
                    <h5>@Html.DisplayFor(modelItem => item.Author) <span class="chat_date">@Html.DisplayFor(modelItem => item.TimeStamp)</span></h5>
                    <p>
                        @Html.DisplayFor(modelItem => item.Message)
                    </p>
                </div>
            }

        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col">
                <label asp-for="Message" class="control-label"></label>
                <textarea asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Post" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

HelloRestApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Chat";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Hello chat app</h1>
</div>

HelloRestApi/Views/Home/Post.cshtml
@{
    ViewData["Title"] = "Post";
}

<h1>Post</h1>

<form action="/home/post" method="post">
    <div class="form-group">
        <label for="author">Message author</label>
        <input type="text" class="form-control" id="author" aria-describedby="authorHelp" placeholder="Enter message author" name="Author">
        <small id="authorHelp" class="form-text text-muted">It's so we know who to blame.</small>
    </div>
    <div class="form-group">
        <label for="messageArea">Message</label>
        <textarea class="form-control" id="messageArea" placeholder="Your message" name="Message"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

HelloRestApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hello chat app</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hello chat app</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Helloes" asp-action="Index">See messages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Helloes" asp-action="Create">Add a message</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Hello chat app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>